version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: factorial-backend
    command: bundle exec rails s -p ${BACKEND_PORT} -b '0.0.0.0'
    volumes:
      - .:/backend-app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    environment:
      - PORT=${BACKEND_PORT}
      - POSTGRES_DATABASE_USERNAME=${POSTGRES_USER}
      - POSTGRES_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
  frontend:
    build:
      context: ./frontend
    container_name: factorial-frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
volumes:
  postgres: